BEGIN TRANSACTION;
CREATE TABLE "table_1" (
	"id"	INTEGER NOT NULL UNIQUE,
	"input_image"	BLOB NOT NULL,
	"output_image"	BLOB NOT NULL,
	"model_prediction"	TEXT NOT NULL,
	"datetime"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)
COMMIT;
